Create Database Retail
Select*from Customer
Select*From Transactions
Select*From Prod_cat_Info

--------------------DATA PREPRATION AND UNDERSTANDING------------------------------
--1.What is the total number of rows in each of the 3 tables in the database?
Select*From(Select Count(Customer_ID) As CUST_COUNT From Customer 
Union
Select Count(Prod_cat_code) AS PROD_COUNT From prod_cat_info
Union
Select Count(transaction_id)  AS TRASAC_COUNT From Transactions) as X

--2.What is the total number of transaction that have a return?
Select Count(total_amt) as 'Return' From [dbo].[Transactions]
Where Total_amt <0
/*3.As you would have noticed , the dates provided across the datasets are not in a correct format.
As first steps, pls convert the date variables into valid date format before proceeding ahead.*/

Alter Table Transactions
Alter Column tran_date date

Alter Table Customer
Alter  Column DOB Date


--4.What is the time range of transaction data avlaiable for analysis? show the output  in month, days , years simultaneously in 3 columns.
Select 
       DATEDIFF(Day, Min(Tran_date),Max(Tran_date)) As DayDiff,
       DATEDIFF(Month,Min(Tran_date),Max(Tran_date) ) As MonthDiff,
       DATEDIFF(Year, Min(Tran_date),Max(Tran_date)) As YearDiff
From Transactions

--5.Which product category does sub-category 'diy' belong to?

Select Distinct Prod_cat_code,Prod_cat
From Prod_cat_info
Where prod_subcat='diy'

-------------------------------------------DATA ANALYSIS---------------------------------------------------
--1.Which Channel is most frequentyly used for transaction?
Select*From [dbo].[Transactions]

 Select Top 1 Store_Type ,COUNT(Store_type)As Frequency From [dbo].[Transactions] 
 Group by Store_Type
 Order By Frequency desc
	
--2.What is the count of Male and Female customer in the Database?

Select Gender,Count(Gender) as M_F_Count
From Customer
Where Gender is Not Null
Group by Gender

--3.From which city do we have maximum number of customer and how many?

Select Top 1 City_code,Count(Customer_id) as Cust_Count
From Customer
Group By city_code
Order by Cust_Count desc

--4.How many sub-categories are there under Books category?

Select Count(Prod_subcat) as Book_Count
From prod_cat_info
Where Prod_cat='Books'

--5.What is max number of Quantity of products  ever ordered?
Select Max(Qty) as Count_of_prod
From Transactions
where Qty>0


--6.What is the net total revenue generated in categories electronics and books?

 Select sum(total_amt) as Revenue 
 from Transactions
 inner join prod_cat_info
 On prod_cat_info.prod_cat_code=Transactions.prod_cat_code
 where prod_cat ='Books' Or prod_cat='Electronics'


--7.How many Customer have>10 trasaction with us, excluding returns?

Select Count(Cust_id) As ToT_Cust
from(
      Select Cust_id,COUNT(Cust_id)as Cust_Count
      From Transactions
      Inner Join Customer
      On cust_id=customer_Id
      Where total_amt>0
      Group by cust_id
      Having COUNT(Cust_id)>10
     ) as X

--8.What is combined revenue earned from "electronics" and "Clothing" categories . From "Flagship store"?

Select Sum(Total_amt) As Revenue
From Transactions
Inner join prod_cat_info
On Transactions.prod_cat_code=Prod_cat_info.prod_cat_code
Where prod_cat='Clothing'
         Or
      prod_cat='Electronics'
         And 
      Store_type like 'Flagship%'

--9.What is the total revenue generated from the male customer in electronic product category? Output should display revenue by product sub-category.

 Select prod_cat_info.prod_subcat,Sum(total_amt) as Revenue From Transactions
 inner join prod_cat_info
 On prod_cat_info.prod_sub_cat_code=Transactions.prod_subcat_code
 inner join Customer
 On Customer.customer_Id=Transactions.cust_id
 Where prod_cat='Electronics' And Gender='M'
 Group By prod_subcat

 --10.What is percentage Sales And Returns By Product sub category? Display only top 5 product sub category in term of sales.

 
 Select Top 5 prod_subcat_code,Sales,[Return],Sales *100.00/total  as [%Sales],
 [Return] *100.00/total as [%Reutrn]
 From(
 Select  X.prod_subcat_code,X.Sales,Y.[Return] ,
 (Select Count(Qty)  From Transactions) as total
 From
 (Select  Prod_subcat_code,Count(Qty ) as Sales
 From Transactions
 Where Qty>0
 Group by prod_subcat_code ) As X
  Inner join
  (Select Prod_subcat_code,Count(Qty) as [Return]
 From Transactions
 Where Qty<0
 Group by prod_subcat_code )as Y
 On X.prod_subcat_code=Y.prod_subcat_code
 ) as A
 Order by Sales desc
 

 /*11.For all the customer Aged Between 25-35 find net total revenue generated by these customers
 in last 30 days from max transaction date available in data*/

 select Customer_id,Sum(Total_amt) as Revenue
 from Customer
 Inner join Transactions
 On Transactions.cust_id=customer_Id
where   Datediff(year,DOB,GETDATE()) between 25 and 35
And   tran_date >=DATEADD(day,-30, (Select Max(tran_date)From Transactions ))
  Group by customer_Id
  Order By Revenue desc

--12.Which product category has seen the max value of return in the last 3 months of transaction?

Select Top 1  prod_cat ,Sum(total_amt) as [Returns]
From Transactions
Inner join prod_cat_info
On prod_cat_info.prod_cat_code=Transactions.prod_cat_code
Where total_amt<0 
And tran_date>=DATEADD(Month,-3,(select Max(tran_date) from Transactions))
Group by prod_cat
Order by [Returns] Asc

--13.Which store-type sells the max products by value of sales amount and by quantity sold?
Select Top 1 Store_type,Sum(total_amt) as Sales,Sum(Cast(Qty as float)) As Tot_Amt
From Transactions
group by Store_type
order by Sales Desc

--14.What are the categories for which average revenue is above the overall average?
Select prod_cat,Avg(total_amt) as Avg_revenue
From Transactions
Inner Join prod_cat_info
On prod_cat_info.prod_cat_code=Transactions.prod_cat_code
Group by prod_cat
Having avg(total_amt)>(Select avg(total_amt) from Transactions)

--15.Find the avg and total revenue by each subcategory for the categories which are among top 5 categories in term of quantity sold.
Select Prod_subcat,Prod_cat,Avg(Total_Amt) as Avg_revenue ,Sum(Total_amt) as Tot_revenue
From Transactions
Inner join prod_cat_info
On prod_cat_info.prod_cat_code=Transactions.prod_cat_code
where prod_cat in (
Select Top 5 prod_cat
From Transactions
Inner Join prod_cat_info
On prod_cat_info.prod_cat_code=Transactions.prod_cat_code
Group by prod_cat
Order by Sum(cast(qty as Float)) desc)
Group by prod_cat,prod_subcat
order by prod_cat,prod_subcat











